### ISSUE TITLE
Unable to sam build

### ISSUE THREAD

**Issue by yeyeric** [iwpnd/fastapi-aws-lambda-example#1]
Hi,

first of all thank you for your tutorial which is the only one dealing about fastapi and serverless out there.

I'm having problem at the step: Stage: Build the deployment package

When I build, I get the following error: 

```
Final incompatible: {pydantic==1.2(wheel), websockets==8.1(wheel), cryptography==2.8(wheel), uvloop==0.14.0(wheel)}
Final missing wheels: {uvloop==0.14.0(wheel)}
PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 42, in execute
    requirements_path=self.manifest_path,
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 137, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 201, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {uvloop==0.14.0(wheel)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 45, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: {uvloop==0.14.0(wheel)}
Builder workflow failed
Traceback (most recent call last):
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 42, in execute
    requirements_path=self.manifest_path,
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 137, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 201, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {uvloop==0.14.0(wheel)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 45, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: {uvloop==0.14.0(wheel)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/__main__.py", line 126, in main
    mode=params.get("mode", None),
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/builder.py", line 125, in build
    return workflow.run()
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflow.py", line 76, in wrapper
    func(self, *args, **kwargs)
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflow.py", line 276, in run
    raise WorkflowFailedError(workflow_name=self.NAME, action_name=action.NAME, reason=str(ex))
aws_lambda_builders.exceptions.WorkflowFailedError: PythonPipBuilder:ResolveDependencies - {uvloop==0.14.0(wheel)}
Build inside container returned response {"jsonrpc": "2.0", "id": 1, "error": {"code": 400, "message": "PythonPipBuilder:ResolveDependencies - {uvloop==0.14.0(wheel)}"}}

Build Failed
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 123589, 'exitReason': 'BuildError', 'exitCode': 1, 'requestId': 'd943b1f2-73e0-42d3-b8fb-2e94d5436dd4', 'installationId': 'acc6ee82-60bf-4a06-a81c-405c230a0da1', 'sessionId': '3600cf82-fe9d-4961-9a97-7ad8a856986b', 'executionEnvironment': 'CLI', 'pyversion': '3.7.6', 'samcliVersion': '0.41.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: PythonPipBuilder:ResolveDependencies - {uvloop==0.14.0(wheel)}
```

I've tried to look online and nothing very significant.

Do you have any idea what could be wrong ?

Thanks

**Comment by iwpnd** [comment]
Hi! Thanks for the kind words.

Can you give me some more info on what exactly did you try to execute, what is in your requirements file and what does your folder structure look like? Is docker properly setup on your machine and does it have access to your hard drive? sam will mount your project folder and therefor will need access. 

Depending on your OS I read about people having success with `pip install wheel` and running `sam build` without the container option. 

With some more background information I’m sure we can set you up. :)

**Comment by yeyeric** [comment]
Hi,

I've followed your tutorial here with my own project. I've tried on both MAC OS X and Windows 10 but same result with the uvloop fails.

Just read your update, can you give me some background on what are the impacts if I remove it ? Sorry I'm a bit new to this. Is it because this has no use for serverless ?

Thanks again !

**Comment by iwpnd** [comment]
> Is it because this has no use for serverless ?

That's right. Uvicorn is an ASGI server, built on uvloop and httptools. You use that to build your FastAPI in your development environment, because otherwise, you would have no server to test on. On Lambda however you don't need a server, because AWS provisions that for you.

So, use `uvicorn` to develop, but don't use it in your app, don't put it into your `requirements.txt`, don't `sam build` it and you're good.

**Comment by yeyeric** [comment]
thank you, it worked for the Sam Build.
Now I'm stuck at deploy stage because it looks like my app is too big:  Unzipped size must be smaller than 262144000 bytes (Service:
                                                                                                                                                                                                         AWSLambdaInternal; Status Code: 400; Error Code:
                                                                                                                                                                                                         InvalidParameterValueException; Request ID:


In my Dockerfile, I'm using:
```
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7
COPY ./app /app
COPY ./app/app/settings/.env /app/app/settings/.env
```

Could it be because the docker image I'm using is too big ? FYI if I use the alpine one, my app doesn't work.

Btw, I've looked into your [dockerfile](https://github.com/iwpnd/fastapi-aws-lambda-example/blob/master/Dockerfile) and you're using uvicorn :)

**Comment by iwpnd** [comment]
> Now I'm stuck at deploy stage because it looks like my app is too big:

Make sure that you only put stuff in your `requirements.txt` that your application needs to run as you see AWS Lambda has certain [limit](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html). If you really need heavy libraries (scikit, pandas, opencv) then I suggest you take another route then deploying with AWS SAM. There are ways to reduce the deployment package size and I'm sure you will find a solution. You will notice that AWS Lambda is not the environment to do the job, you will notice that you don't need e.g. `pandas`  or you find a way to slim down that deployment package by building it in a docker container yourself and ship the zip file you build in there separately from AWS SAM.

Checkout [this to learn how to slim down your package with serverless instead](https://tech.europace.de/slimifying-aws-lambdas/), [this, if you want to build your own deployment packages](https://blog.quiltdata.com/an-easier-way-to-build-lambda-deployment-packages-with-docker-instead-of-ec2-9050cd486ba8) and [this to use pre-build lambda packages](https://github.com/ryfeus/lambda-packs).

Either way, that's not the scope of my tutorial.

> Could it be because the docker image I'm using is too big? FYI if I use the alpine one, my app doesn't work.

You need that Dockerfile if you want to run your app locally, hence the uvicorn in it, it is not necessary for the deployment of an AWS Lambda function in the scope of my tutorial.


Closing this now. Good luck, have fun! :)
