### ISSUE TITLE
unable to access to /docs

### ISSUE THREAD

**Issue by yeyeric** [iwpnd/fastapi-aws-lambda-example#2]
Hi (again),

I've managed to deploy properly your app (I was trying mine at first and I successfully deployed it, but I was unable to access the /docs page, so decided to go with yours).

With your app, cloning your project, and building, packaging and deploying it, I have an error when access the /docs page, is that expected ?
![Pb api](https://user-images.githubusercontent.com/43412665/75930809-bccca680-5e73-11ea-8c63-ca65758f2aa6.PNG)

FYI that's the same error I also have when accessing my project, even if I put maximum RAM it doesn't change anything.

Looking at the log doesn't give anything relevant (or maybe I didn't look at the proper place ?)
START RequestId: 8681588b-b3c5-4827-a94a-0e3b4cbddaf0 Version: $LATEST
END RequestId: 8681588b-b3c5-4827-a94a-0e3b4cbddaf0
REPORT RequestId: 8681588b-b3c5-4827-a94a-0e3b4cbddaf0 Duration: 3.82 ms Billed Duration: 100 ms Memory Size: 128 MB Max Memory Used: 85 MB Init Duration: 562.30 ms

I can only see lines like this

Would you have any idea ?

Thanks

Edit: just tried to access the /ping, and it works ! Why isn't it the case with /docs ?

**Comment by iwpnd** [comment]
It's something about the way FastAPI handles the basepath of your application.
If you do not plan to use a custom domain for you API, then set:

```python
app = FastAPI(
    title=PROJECT_NAME,
    openapi_prefix="/Prod" # name of your stage
)
```

and it should work. There is a discussion over [FastAPI](https://github.com/tiangolo/fastapi/issues/829) about this.

**Comment by yeyeric** [comment]
Oh ok, I thought I was again doing something wrong.
will try that shortly but I’m pretty sure it’s the reason
Thanks again !

**Comment by KurtKline** [comment]
I would recommend to update `openapi_prefix="/Prod"` to `openapi_prefix="/prod"` (lowercase prod) in your repository. When I first deployed with `Prod`, /docs wouldn't load. But when I switched it to `prod`, then it began to load properly. I think because the deployment `StageName` is `prod`, and maybe these need to match?

**Comment by MuhammadAshiqAmeer** [comment]
The only thing needed:
app = FastAPI(root_path="/prod")
