### ISSUE TITLE
/docs and /redoc not loading when deployed on AWS

### ISSUE THREAD

**Issue by KurtKline** [iwpnd/fastapi-aws-lambda-example#3]
First of all, thank you very much for your tutorial. I was able to deploy your example project to AWS, and when I use the URL with `/prod/ping` I get the expected result: 

{
ping: "pong!"
}

However, when I try to use the URL with `/prod/docs` or `prod/redoc` I get a "Failed to load API definition" error.

![image](https://user-images.githubusercontent.com/20330796/82737523-de7e5100-9d31-11ea-81bf-021bea7e7e64.png)

Any ideas why this may be happening?

**Comment by iwpnd** [comment]
Hi, see #2

**Comment by KurtKline** [comment]
Ah, thank you. Sorry, should have looked through the closed issues first.
